name: Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        sdk: [3.1, stable, beta]
        include:
 #         - os: ubuntu-latest
 #           output-name: yt-splitter-linux
          - os: windows-latest
            output-name: yt-splitter-windows.exe

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: mkdir build
      - run: dart pub get
      - run: dart compile exe bin/yt_splitter.dart -v -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v4
        with:
          name: native-executables
          path: build
